### ISSUE TITLE
Encoding::UndefinedConversionError: "\x89" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by ohaddahan** [camertron/mosaico-rails#3]
During `db:migrate` I'm getting this error.
I using PostgreSQL, I updated everything (Rails, Ruby, etc.) to the latest versions.

```
Encoding::UndefinedConversionError: "\x89" from ASCII-8BIT to UTF-8
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/generated-assets-2.1.1/lib/generated-assets/entry.rb:24:in `write'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/generated-assets-2.1.1/lib/generated-assets/entry.rb:24:in `write_to'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/generated-assets-2.1.1/lib/generated-assets/manifest.rb:45:in `block in write_files'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/generated-assets-2.1.1/lib/generated-assets/manifest.rb:44:in `each'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/generated-assets-2.1.1/lib/generated-assets/manifest.rb:44:in `write_files'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/generated-assets-2.1.1/lib/generated-assets/manifest.rb:25:in `apply!'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/generated-assets-2.1.1/lib/generated-assets/railtie.rb:13:in `block in <class:Railtie>'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
/Users/ohaddahan/Projects/auto-gram/config/environment.rb:5:in `<top (required)>'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/airbrake-8.0.0/lib/airbrake/rake.rb:17:in `execute'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/command.rb:48:in `invoke'
/Users/ohaddahan/.rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
```

**Comment by camertron** [comment]
Hey @ohaddahan thanks for the bug report! Looks like it was a problem with the [generated-assets](https://github.com/camertron/generated-assets) gem (which I also maintain). I just fixed the issue and published a new version of the gem, so running `bundle update generated-assets` should fix your problem :)

**Comment by ohaddahan** [comment]
@camertron Thanks :)
